// src/pages/booking/new.tsx
import { ChangeEvent, FormEvent, useState } from "react";
import { BookingForm } from "types";

export default function NewBooking() {
  function handleFormSubmit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault();
    let form = new FormData(e.currentTarget);
    let data = Object.fromEntries(form.entries()) as unknown as BookingForm;

    if (verifySubmit(data)) {
      console.log(data);
      postData(data);
    }
  }

  const [vehicleRequired, setVehicleRequired] = useState<boolean>(false);

  const [vehicles, setVehicles] = useState<string[]>([]);

  function handleCheckboxChange(e: ChangeEvent<HTMLInputElement>) {
    if (e.target.checked) {
      setVehicles([...vehicles, e.target.name]);
    } else {
      setVehicles(vehicles.filter((vehicle) => vehicle !== e.target.name));
    }

    if (vehicles.length === 0 && e.target.checked) {
      setVehicleRequired(true);
    } else if (vehicles.length === 1 && !e.target.checked) {
      setVehicleRequired(false);
    }
  }

  async function postData(data: BookingForm) {
    await fetch("/api/booking", {
      method: "POST",
      body: JSON.stringify(data),
      headers: {
        "Content-Type": "application/data",
      },
    })
      .then((res) => {
        if (!res.ok) {
          throw new Error("Network response was not ok");
        }
        alert("Bokning skickad");
      })
      .catch((err) => {
        console.error(err);
        alert("Något gick fel");
      });
  }

  function verifySubmit(data: BookingForm) {
    if (!data.firstName) {
      alert("Du måste ange ett förnamn");
      return false;
    }
    if (!data.lastName) {
      alert("Du måste ange ett efternamn");
      return false;
    }
    if (!data.email) {
      alert("Du måste ange en e-post");
      return false;
    }
    if (data.email !== data.confirmEmail) {
      alert("E-post matchar inte bekräftelse");
      return false;
    }
    if (!data.phone) {
      alert("Du måste ange ett telefonnummer");
      return false;
    }
    if (!data.arrivalDate) {
      alert("Du måste ange ett ankomstdatum");
      return false;
    }
    if (!data.departureDate) {
      alert("Du måste ange ett avresedatum");
      return false;
    }
    if (data.arrivalDate >= data.departureDate) {
      alert("Avresedatum måste vara efter ankomstdatum");
      return false;
    }
    if (!data.agreeToPolicy) {
      alert("Du måste godkänna bokningsvillkoren");
      return false;
    }
    if (!data.numberOfPersons) {
      alert("Du måste ange antal personer");
      return false;
    }
    if (vehicleRequired) {
      if (!data.vehicleRegNumber) {
        alert("Du måste ange registreringsnummer på fordonet");
        return false;
      }
    }

    return true;
  }

  return (
    <div className="container flex p-5">
      <form
        onSubmit={handleFormSubmit}
        className="flex flex-col gap-3 bg-slate-300 p-4"
      >
        <h3 className="text-xl font-semibold">Kontaktuppgifter</h3>
        <label htmlFor="firstName">Förnamn*</label>
        <input type="text" name="firstName" id="firstName" />
        <label htmlFor="lastName">Efternamn*</label>
        <input type="text" name="lastName" id="lastName" />
        <label htmlFor="email">E-post*</label>
        <input type="email" name="email" id="email" />
        <label htmlFor="confirmEmail">Bekräfta E-post*</label>
        <input type="email" name="confirmEmail" id="confirmEmail" />
        <label htmlFor="phone">Telefon* (inkl. landsnummer)</label>
        <input type="tel" name="phone" id="phone" />

        <h3 className="mt-5 text-xl font-semibold">Boende*</h3>
        <div className="flex flex-col gap-4">
          <label htmlFor="arrivalDate">Ankomstdatum*</label>
          <input type="date" name="arrivalDate" id="arrivalDate" />
          <label htmlFor="departureDate">Avresedatum*</label>
          <input type="date" name="departureDate" id="departureDate" />
        </div>

        <div className="flex flex-col gap-2">
          <h4 className="font-semibold">Välj det boende du vill ha</h4>
          <div className="checkbox-row">
            <label htmlFor="stuga">Stuga</label>
            <input type="checkbox" name="stuga" id="stuga" />
          </div>
          <div className="checkbox-row">
            <label htmlFor="husvagn">Husvagn</label>
            <input
              type="checkbox"
              name="husvagn"
              id="husvagn"
              onChange={handleCheckboxChange}
            />
          </div>

          <div className="checkbox-row">
            <label htmlFor="husbil">Husbil</label>
            <input
              type="checkbox"
              name="husbil"
              id="husbil"
              onChange={handleCheckboxChange}
            />
          </div>
          <div className="checkbox-row">
            <label htmlFor="tält">Tält</label>
            <input type="checkbox" name="tält" id="tält" />
          </div>
        </div>

        {vehicleRequired && (
          <div className="flex flex-col">
            <label htmlFor="vehicleLength">Längd på fordonet</label>
            <input type="number" name="vehicleLength" id="vehicleLength" />
            <label htmlFor="vehicleWidth">Bredd på fordonet</label>
            <input type="number" name="vehicleWidth" id="vehicleWidth" />
            <label htmlFor="vehicleRegNumber">Registreringsnummer*</label>
            <input type="text" name="vehicleRegNumber" id="vehicleRegNumber" />
          </div>
        )}

        <label htmlFor="numberOfPersons">Antal personer*</label>
        <input type="number" name="numberOfPersons" id="numberOfPersons" />

        <h3 className="mt-5 text-xl font-semibold">Övrigt</h3>
        <div className="flex flex-col">
          <label htmlFor="önskemål">Önskemål</label>
          <textarea name="önskemål" id="önskemål"></textarea>
        </div>
        <div>
          <label htmlFor="agreeToPolicy" className="mr-3">
            Godkännande
          </label>
          <input type="checkbox" name="agreeToPolicy" id="agreeToPolicy" />
          <p className="mt-4">
            Vi behöver ovan uppgifter för att kunna fullfölja er bokning av
            boende hos oss och vi kommer inte att dela dessa uppgifter med
            tredje part.
          </p>
        </div>

        <button type="submit" className="btn btn-primary">
          Skicka bokning
        </button>
      </form>
    </div>
  );
}

// src/routes/booking/new/+page.svelte
<script lang="ts">
	import { toast, Toaster } from 'svelte-french-toast';

	let caravanChecked = false;
	let motorhomeChecked = false;

	let caravanData: {
		length: number;
		width: number;
		regNr: string;
	} = {
		length: 0,
		width: 0,
		regNr: ''
	};

	let motorhomeData: {
		length: number;
		width: number;
		regNr: string;
	} = {
		length: 0,
		width: 0,
		regNr: ''
	};

	async function postForm(form: Event) {
		const formData = new FormData(form.target as HTMLFormElement);
		let data = Object.fromEntries(formData.entries());

		// Make a string of the type of accommodation
		let typeOfAccommodation = '';
		if (data.tent) {
			typeOfAccommodation += 'Tält, ';
		}
		if (data.caravan) {
			typeOfAccommodation += 'Husvagn, ';
			caravanData.length = Number(data.caravanLength);
			caravanData.width = Number(data.caravanWidth);
			caravanData.regNr = data.caravanRegNr as string;

			delete data.caravanLength;
			delete data.caravanWidth;
			delete data.caravanRegNr;

			data.caravanData = JSON.stringify(caravanData);
		}
		if (data.motorhome) {
			typeOfAccommodation += 'Husbil, ';
			motorhomeData.length = Number(data.motorhomeLength);
			motorhomeData.width = Number(data.motorhomeWidth);
			motorhomeData.regNr = data.motorhomeRegNr as string;

			delete data.motorhomeLength;
			delete data.motorhomeWidth;
			delete data.motorhomeRegNr;

			data.motorhomeData = JSON.stringify(motorhomeData);
		}
		if (data.cottage) {
			typeOfAccommodation += 'Stuga, ';
		}
		typeOfAccommodation = typeOfAccommodation.slice(0, -2);

		// Remove the checkboxes from the data object
		delete data.tent;
		delete data.caravan;
		delete data.motorhome;
		delete data.cottage;

		// Add the type of accommodation to the data object
		data.typeOfAccommodation = typeOfAccommodation;

		// Check if date is valid
		if (data.arrivalDate > data.departureDate) {
			alert('Ankomstdatum kan inte vara senare än avresedatum');
			return;
		}
		if (data.arrivalDate < new Date().toISOString().slice(0, 10)) {
			alert('Ankomstdatum kan inte vara tidigare än dagens datum');
			return;
		}

		// Check if number of persons is valid
		if (data.numberOfPersons < '1') {
			alert('Antal personer måste vara minst 1');
			return;
		}

		// Check if gdpr is checked
		if (!data.gdpr) {
			alert('Du måste godkänna att dina uppgifter lagras');
			return;
		}

		// Check if motorhome reg nr is filled in
		if (data.motorhomeRegNr === '' && data.motorhomeLength) {
			alert('Du måste fylla i registreringsnummer på husbilen');
			return;
		}

		// Check if caravan reg nr is filled in
		if (data.caravanRegNr === '' && data.caravanLength) {
			alert('Du måste fylla i registreringsnummer på husvagnen');
			return;
		}

		try {
			console.log(data);

			await fetch(`/api/booking`, {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json'
				},
				body: JSON.stringify(data)
			}).then(async (data) => {
				const body = await data.json();
				if (data.status !== 200 || body.error) {
					alert('Något gick fel, försök igen');
					return;
				}
				console.log('Success');
				console.log('Booking id:', body._id);
				const form: HTMLFormElement = document.getElementById('form') as HTMLFormElement;
				form.reset();
				toast.success('Bokning skickad!', {
					duration: 5000
				});
			});
		} catch (error) {
			console.error('Error adding document: ', error);
			toast.error('Något gick fel, försök igen', {
				duration: 5000
			});
		}
	}
</script>

<section>
	<Toaster />
	<form on:submit={postForm} id="form" class="container flex flex-col max-w-xl">
		<h1 class="text-center text-3xl font-semibold">Bokningsformulär</h1>
		<label for="firstName">Förnamn</label>
		<input type="text" name="firstName" id="firstName" required />
		<label for="lastName">Efternamn</label>
		<input type="text" name="lastName" id="lastName" required />
		<label for="email">E-post</label>
		<input type="email" name="email" id="email" required />
		<label for="phone">Telefonnummer</label>
		<input type="tel" name="phone" id="phone" required />
		<label for="dateArrival">Ankomstdatum</label>
		<input type="date" name="dateArrival" id="dateArrival" required />
		<label for="dateDepart">Avresedatum</label>
		<input type="date" name="dateDepart" id="dateDepart" required />
		<label for="numberOfPersons">Antal Personer</label>
		<input type="number" name="numberOfPersons" id="numberOfPersons" required />
		<div class="divider" />
		<p>Typ av boende</p>
		<div class="type">
			<div class="checkbox-row">
				<input type="checkbox" name="tent" id="tent" />
				<label for="tent">Tält</label>
			</div>
			<div class="checkbox-row">
				<input type="checkbox" name="caravan" id="caravan" bind:checked={caravanChecked} />
				<label for="caravan">Husvagn</label>
			</div>
			<div class="checkbox-row">
				<input type="checkbox" name="motorhome" id="motorhome" bind:checked={motorhomeChecked} />
				<label for="motorhome">Husbil</label>
			</div>
			<div class="checkbox-row">
				<input type="checkbox" name="cottage" id="cottage" />
				<label for="cottage">Stuga</label>
			</div>
		</div>

		{#if motorhomeChecked}
			<label for="motorhomeLength">Längd på husbil</label>
			<input type="number" name="motorhomeLength" id="motorhomeLength" />
			<label for="motorhomeWidth">Bredd på husbil</label>
			<input type="number" name="motorhomeWidth" id="motorhomeWidth" />
			<label for="motorhomeRegNr">Registeringsnummer på husbil*</label>
			<input type="text" name="motorhomeRegNr" id="motorhomeRegNr" />
		{/if}

		{#if caravanChecked}
			<label for="caravanLength">Längd på husvagn</label>
			<input type="number" name="caravanLength" id="caravanLength" />
			<label for="caravanWidth">Bredd på husvagn</label>
			<input type="number" name="caravanWidth" id="caravanWidth" />
			<label for="caravanRegNr">Registeringsnummer på husvagn</label>
			<input type="text" name="caravanRegNr" id="caravanRegNr" />
		{/if}

		<div class="divider" />

		<label for="message">Meddelande</label>
		<textarea name="message" id="message" cols="30" rows="10" />

		<div class="divider" />

		<p>
			Genom att skicka detta formulär godkänner du att vi lagrar dina uppgifter i vårt
			bokningssystem.
		</p>

		<div class="checkbox-row">
			<input type="checkbox" name="gdpr" id="gdpr" required />
			<label for="gdpr">Jag godkänner att mina uppgifter lagras</label>
		</div>

		<button type="submit" class="btn mb-5">Skicka</button>
	</form>
</section>

<style>
	input[type='text'],
	input[type='email'],
	input[type='tel'],
	input[type='number'],
	input[type='date'] {
		@apply input input-bordered w-full;
	}

	input[type='checkbox'] {
		@apply checkbox;
	}

	textarea {
		@apply textarea textarea-bordered w-full;
	}

	label {
		@apply label-text;
	}

	.checkbox-row {
		@apply flex items-center gap-2 mb-2;
	}
</style>
